# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEcZltfgosM9J5uFu6Wt9DK1_L3xgl8K
"""


story=[]

"""**STORY 1**"""

s=[]
i=0

story.append("""To Your Good Health!

Long, long ago there lived a king who was such a mighty monarch that
whenever he sneezed every one in the whole country had to say 'To your
good health!' Every one said it except the shepherd with the staring
eyes, and he would not say it.

The king heard of this and was very angry, and sent for the shepherd to
appear before him.

The shepherd came and stood before the throne, where the king sat
looking very grand and powerful. But however grand or powerful he might
be the shepherd did not feel a bit afraid of him.

'Say at once, "To my good health!"' cried the king.

'To my good health!' replied the shepherd.

'To mine--to mine, you rascal, you vagabond!' stormed the king.

'To mine, to mine, your Majesty,' was the answer.

'But to mine--to my own,' roared the king, and beat on his breast in a
rage.

'Well, yes; to mine, of course, to my own,' cried the shepherd, and
gently tapped his breast.

The king was beside himself with fury and did not know what to do, when
the Lord Chamberlain interfered:

'Say at once--say this very moment: "To your health, your Majesty"; for
if you don't say it you'll lose your life, whispered he.

'No, I won't say it till I get the princess for my wife,' was the
shepherd's answer. Now the princess was sitting on a little throne
beside the king, her father, and she looked as sweet and lovely as a
little golden dove. When she heard what the shepherd said she could not
help laughing, for there is no denying the fact that this young shepherd
with the staring eyes pleased her very much; indeed he pleased her
better than any king's son she had yet seen.

But the king was not as pleasant as his daughter, and he gave orders to
throw the shepherd into the white bear's pit.

The guards led him away and thrust him into the pit with the white bear,
who had had nothing to eat for two days and was very hungry. The door of
the pit was hardly closed when the bear rushed at the shepherd; but when
it saw his eyes it was so frightened that it was ready to eat itself. It
shrank away into a corner and gazed at him from there, and, in spite of
being so famished, did not dare to touch him, but sucked its own paws
from sheer hunger. The shepherd felt that if he once removed his eyes
off the beast he was a dead man, and in order to keep himself awake he
made songs and sang them, and so the night went by.

Next morning the Lord Chamberlain came to see the shepherd's bones, and
was amazed to find him alive and well. He led him to the king, who fell
into a furious passion, and said: 'Well, you have learned what it is to
be very near death, and now will you say "To my good health"?'

But the shepherd answered: 'I am not afraid of ten deaths! I will only
say it if I may have the princess for my wife.'

'Then go to your death,' cried the king; and ordered him to be thrown
into the den with the wild boars. The wild boars had not been fed for a
week, and when the shepherd was thrust into their don they rushed at him
to tear him to pieces. But the shepherd took a little flute out of the
sleeve of his jacket and began to play a merry tune, on which the wild
boars first of all shrank shyly away, and then got up on their hind legs
and danced gaily. The shepherd would have given anything to be able to
laugh, they looked so funny; but he dared not stop playing, for he knew
well enough that the moment he stopped they would fall upon him and tear
him to pieces. His eyes were of no use to him here, for he could not
have stared ten wild boars in the face at once; so he kept on playing,
and the wild boars danced very slowly, as if in a minuet, then by
degrees he played faster and faster till they could hardly twist and
turn quickly enough, and ended by all falling over each other in a heap,
quite exhausted and out of breath.

Then the shepherd ventured to laugh at last; and he laughed so long
and so loud that when the Lord Chamberlain came early in the morning,
expecting to find only his bones, the tears were still running down his
cheeks from laughter.

As soon as the king was dressed the shepherd was again brought before
him; but he was more angry than ever to think the wild boars had not
torn the man to bits, and he said: 'Well, you have learned what it feels
to be near ten deaths, now say "To my good health!"'

But the shepherd broke in with, 'I do not fear a hundred deaths, and I
will only say it if I may have the princess for my wife.'

'Then go to a hundred deaths!' roared the king, and ordered the shepherd
to be thrown down the deep vault of scythes.

The guards dragged him away to a dark dungeon, in the middle of which
was a deep well with sharp scythes all round it. At the bottom of the
well was a little light by which one could see if anyone was thrown in
whether he had fallen to the bottom.

When the shepherd was dragged to the dungeons he begged the guards to
leave him alone a little while that he might look down into the pit of
scythes; perhaps he might after all make up his mind to say 'To your
good health' to the king. So the guards left him alone and he stuck up
his long stick near the well, hung his cloak round the stick and put his
hat on the top. He also hung his knapsack up inside the cloak so that it
might seem to have some body within it. When this was done he called out
to the guards and said that he had considered the matter but after all
he could not make up his mind to say what the king wished. The guards
came in, threw the hat and cloak, knapsack and stick all down the well
together, watched to see how they put out the light at the bottom and
came away, thinking that now there really was an end of the shepherd.
But he had hidden in a dark corner and was laughing to himself all the
time.

Quite early next morning came the Lord Chamberlain, carrying a lamp and
he nearly fell backwards with surprise when he saw the shepherd alive
and well. He brought him to the king, whose fury was greater than ever,
but who cried:

'Well, now you have been near a hundred deaths; will you say: "To your
good health"?'

But the shepherd only gave the same answer:

'I won't say it till the princess is my wife.'

'Perhaps after all you may do it for less,' said the king, who saw that
there was no chance of making away with the shepherd; and he ordered the
state coach to be got ready, then he made the shepherd get in with him
and sit beside him, and ordered the coachman to drive to the silver
wood. When they reached it he said: 'Do you see this silver wood? Well,
if you will say, "To your good health," I will give it to you.'

The shepherd turned hot and cold by turns, but he still persisted:

'I will not say it till the princess is my wife.'

The king was much vexed; he drove further on till they came to a
splendid castle, all of gold, and then he said:

'Do you see this golden castle? Well, I will give you that too, the
silver wood and the golden castle, if only you will say that one thing
to me: "To your good health."'

The shepherd gaped and wondered and was quite dazzled, but he still
said:

'No; I will not say it till I have the princess for my wife.'

This time the king was overwhelmed with grief, and gave orders to drive
on to the diamond pond, and there he tried once more.

'Do you see this diamond pond? I will give you that too, the silver
wood and the golden castle and the diamond pond. You shall have them
all--all--if you will but say: "To your good health!"'

The shepherd had to shut his staring eyes tight not to be dazzled with
the brilliant pond, but still he said:

'No, no; I will not say it till I have the princess for my wife.'

Then the king saw that all his efforts were useless, and that he might
as well give in, so he said:

'Well, well, it's all the same to me--I will give you my daughter to
wife; but, then, you really and truly must say to me: "To your good
health."'

'Of course I'll say it; why should I not say it? It stands to reason
that I shall say it then.'

At this the king was more delighted than anyone could have believed.
He made it known all through the country that there were to be great
rejoicings, as the princess was going to be married. And everyone
rejoiced to think that the princess, who had refused so many royal
suitors, should have ended by falling in love with the staring-eyed
shepherd.

There was such a wedding as had never been seen. Everyone ate and drank
and danced. Even the sick were feasted, and quite tiny new-born children
had presents given them.

But the greatest merry-making was in the king's palace; there the best
bands played and the best food was cooked; a crowd of people sat down to
table, and all was fun and merry-making.

And when the groomsman, according to custom, brought in the great boar's
head on a big dish and placed it before the king so that he might carve
it and give everyone a share, the savoury smell was so strong that the
king began to sneeze with all his might.

'To your very good health,' cried the shepherd before anyone else, and
the king was so delighted that he did not regret having given him his
daughter.

In time, when the old king died, the shepherd succeeded him. He made a
very good king and never expected his people to wish him well against
their wills; but, all the same, everyone did wish him well, for they all
loved him.
""")
story

# List of tuples containing questions and their corresponding answers
t = [
    ("Why did everyone in the kingdom say 'To your good health!' when the king sneezed?", "Because it was a royal order, and everyone in the kingdom had to say it whenever the king sneezed."),
    ("Who was the only person that refused to say 'To your good health!' to the king?", "A shepherd with staring eyes refused to say it."),
    ("What was the shepherd’s condition for saying 'To your good health!'", "He would only say it if he could marry the princess."),
    ("What happened when the shepherd was thrown into the white bear’s pit?", "The bear was so frightened by the shepherd's staring eyes that it didn’t attack him."),
    ("How did the shepherd survive the wild boars?", "He played a merry tune on his flute, which made the boars dance until they were exhausted."),
    ("How did the shepherd trick the guards in the dungeon with the scythe pit?", "He dressed a stick with his cloak, hat, and knapsack to make it look like a body and hid in the corner."),
    ("What did the king offer the shepherd to say the words 'To your good health!'", "The silver wood, the golden castle, and the diamond pond."),
    ("Did the shepherd accept any of the king’s offers?", "No, he insisted on marrying the princess before he would say the words."),
    ("When did the shepherd finally say 'To your very good health!'", "During the wedding feast when the king sneezed while the boar’s head was being served."),
    ("What kind of king did the shepherd become?", "A beloved king who never forced his people to wish him well and ruled justly.")
]

s.append(t)  # Append answer to the second sublist

# Accessing the first question and its corresponding answer


"""**STORY 2**

"""

story.append("""Lovely Ilonka
There was once a king's son who told his father that he wished to marry.

'No, no!' said the king; 'you must not be in such a hurry. Wait till you
have done some great deed. My father did not let me marry till I had won
the golden sword you see me wear.'

The prince was much disappointed, but he never dreamed of disobeying his
father, and he began to think with all his might what he could do. It
was no use staying at home, so one day he wandered out into the world to
try his luck, and as he walked along he came to a little hut in which he
found an old woman crouching over the fire.

'Good evening, mother. I see you have lived long in this world; do you
know anything about the three bulrushes?'

'Yes, indeed, I've lived long and been much about in the world, but I
have never seen or heard anything of what you ask. Still, if you will
wait till to-morrow I may be able to tell you something.'

Well, he waited till the morning, and quite early the old woman appeared
and took out a little pipe and blew in it, and in a moment all the crows
in the world were flying about her. Not one was missing. Then she asked
if they knew anything about the three bulrushes, but not one of them
did.

The prince went on his way, and a little further on he found another hut
in which lived an old man. On being questioned the old man said he knew
nothing, but begged the prince to stay overnight, and the next morning
the old man called all the ravens together, but they too had nothing to
tell.

The prince bade him farewell and set out. He wandered so far that he
crossed seven kingdoms, and at last, one evening, he came to a little
house in which was an old woman.

'Good evening, dear mother,' said he politely.

'Good evening to you, my dear son,' answered the old woman. 'It is
lucky for you that you spoke to me or you would have met with a horrible
death. But may I ask where are you going?'

'I am seeking the three bulrushes. Do you know anything about them?'

'I don't know anything myself, but wait till to-morrow. Perhaps I can
tell you then.' So the next morning she blew on her pipe, and lo!
and behold every magpie in the world flew up. That is to say, all the
magpies except one who had broken a leg and a wing. The old woman sent
after it at once, and when she questioned the magpies the crippled one
was the only one who knew where the three bulrushes were.

Then the prince started off with the lame magpie. They went on and on
till they reached a great stone wall, many, many feet high.

'Now, prince,' said the magpie, 'the three bulrushes are behind that
wall.'

The prince wasted no time. He set his horse at the wall and leaped over
it. Then he looked about for the three bulrushes, pulled them up and
set off with them on his way home. As he rode along one of the bulrushes
happened to knock against something. It split open and, only think! out
sprang a lovely girl, who said: 'My heart's love, you are mine and I am
yours; do give me a glass of water.'

But how could the prince give it her when there was no water at hand?
So the lovely maiden flew away. He split the second bulrush as an
experiment and just the same thing happened.

How careful he was of the third bulrush! He waited till he came to a
well, and there he split it open, and out sprang a maiden seven times
lovelier than either of the others, and she too said: 'My heart's love,
I am yours and you are mine; do give me a glass of water.'

This time the water was ready and the girl did not fly away, but she
and the prince promised to love each other always. Then they set out for
home.

They soon reached the prince's country, and as he wished to bring his
promised bride back in a fine coach he went on to the town to fetch one.
In the field where the well was, the king's swineherds and cowherds were
feeding their droves, and the prince left Ilonka (for that was her name)
in their care.

Unluckily the chief swineherd had an ugly old daughter, and whilst the
prince was away he dressed her up in fine clothes, and threw Ilonka into
the well.

The prince returned before long, bringing with him his father and mother
and a great train of courtiers to escort Ilonka home. But how they all
stared when they saw the swineherd's ugly daughter! However, there was
nothing for it but to take her home; and, two days later, the prince
married her, and his father gave up the crown to him.

But he had no peace! He knew very well he had been cheated, though he
could not think how. Once he desired to have some water brought him from
the well into which Ilonka had been thrown. The coachman went for it
and, in the bucket he pulled up, a pretty little duck was swimming.
He looked wonderingly at it, and all of a sudden it disappeared and he
found a dirty looking girl standing near him. The girl returned with him
and managed to get a place as housemaid in the palace.

Of course she was very busy all day long, but whenever she had a little
spare time she sat down to spin. Her distaff turned of itself and her
spindle span by itself and the flax wound itself off; and however much
she might use there was always plenty left.

When the queen--or, rather, the swineherd's daughter--heard of this,
she very much wished to have the distaff, but the girl flatly refused
to give it to her. However, at last she consented on condition that she
might sleep one night in the king's room. The queen was very angry, and
scolded her well; but as she longed to have the distaff she consented,
though she gave the king a sleeping draught at supper.

Then the girl went to the king's room looking seven times lovelier than
ever. She bent over the sleeper and said: 'My heart's love, I am yours
and you are mine. Speak to me but once; I am your Ilonka.' But the king
was so sound asleep he neither heard nor spoke, and Ilonka left the
room, sadly thinking he was ashamed to own her.

Soon after the queen again sent to say that she wanted to buy the
spindle. The girl agreed to let her have it on the same conditions as
before; but this time, also, the queen took care to give the king a
sleeping draught. And once more Ilonka went to the king's room and spoke
to him; whisper as sweetly as she might she could get no answer.

Now some of the king's servants had taken note of the matter, and warned
their master not to eat and drink anything that the queen offered him,
as for two nights running she had given him a sleeping draught. The
queen had no idea that her doings had been discovered; and when, a few
days later, she wanted the flax, and had to pay the same price for it,
she felt no fears at all.

At supper that night the queen offered the king all sorts of nice things
to eat and drink, but he declared he was not hungry, and went early to
bed.

The queen repented bitterly her promise to the girl, but it was too late
to recall it; for Ilonka had already entered the king's room, where he
lay anxiously waiting for something, he knew not what. All of a sudden
he saw a lovely maiden who bent over him and said: 'My dearest love, I
am yours and you are mine. Speak to me, for I am your Ilonka.'

At these words the king's heart bounded within him. He sprang up and
embraced and kissed her, and she told him all her adventures since the
moment he had left her. And when he heard all that Ilonka had suffered,
and how he had been deceived, he vowed he would be revenged; so he gave
orders that the swineherd, his wife and daughter should all be hanged;
and so they were.

The next day the king was married, with great rejoicings, to the fair
Ilonka; and if they are not yet dead--why, they are still living.


""")

t = [
    ("Why did the prince decide to leave home and travel the world?",
     "The prince decided to leave home and travel the world because his father told him that he could not marry until he had done some great deed. The prince wanted to fulfill this requirement and find the three bulrushes."),

    ("What was the purpose of the old woman blowing into a pipe, and what creatures did she summon?",
     "The old woman blew into a pipe to summon all the crows in the world to help her find out information about the three bulrushes. However, none of the crows knew anything about them."),

    ("What happened each time the prince split open one of the first two bulrushes?",
     "Each time the prince split open one of the first two bulrushes, a lovely maiden sprang out, but both times the maiden flew away because the prince was unable to give her a glass of water."),

    ("Why did Ilonka disappear the first two times she came out of the bulrushes?",
     "Ilonka disappeared the first two times because the prince could not give her a glass of water, which she requested, and without it, she flew away."),

    ("How did the swineherd’s daughter end up in place of Ilonka?",
     "The swineherd's daughter was dressed in fine clothes by the chief swineherd while the prince was away. She then took Ilonka's place when Ilonka was thrown into the well."),

    ("Why do you think the prince had no peace after marrying the swineherd’s daughter?",
     "The prince had no peace because he knew he had been tricked and that he had married the wrong woman, although he couldn’t initially figure out how the deception occurred."),

    ("What magical traits did Ilonka show when working as a housemaid in the palace?",
     "Ilonka demonstrated magical traits when she spun flax using a distaff that turned by itself, and her spindle spun by itself, always providing an abundant supply of flax without running out."),

    ("How did the queen prevent the king from realizing who Ilonka really was during her first two visits to his room?",
     "The queen gave the king a sleeping draught both times, causing him to sleep through Ilonka's visit and preventing him from recognizing her."),

    ("Do you think the punishment given to the swineherd’s family was fair? Why or why not?",
     "The punishment given to the swineherd’s family—being hanged—might be seen as harsh, but from the prince's perspective, it was a form of revenge for their deceit and the suffering Ilonka endured."),

    ("What lessons do you think this story tries to teach the reader?",
     "The story teaches lessons about honesty, loyalty, the consequences of deceit, and the importance of perseverance and true love. It also suggests that one must be patient and careful in seeking one's desires.")
]
s.append(t)

"""**STORY 3**

"""

story.append("""


The Story of the Seven Simons

Far, far away, beyond all sorts of countries, seas and rivers, there
stood a splendid city where lived King Archidej, who was as good as he
was rich and handsome. His great army was made up of men ready to obey
his slightest wish; he owned forty times forty cities, and in each city
he had ten palaces with silver doors, golden roofs, and crystal windows.
His council consisted of the twelve wisest men in the country, whose
long beards flowed down over their breasts, each of whom was as learned
as a whole college. This council always told the king the exact truth.

Now the king had everything to make him happy, but he did not enjoy
anything because he could not find a bride to his mind.

One day, as he sat in his palace looking out to sea, a great ship sailed
into the harbour and several merchants came on shore. Said the king to
himself: 'These people have travelled far and beheld many lands. I will
ask them if they have seen any princess who is as clever and as handsome
as I am.'

So he ordered the merchants to be brought before him, and when they came
he said: 'You have travelled much and visited many wonders. I wish to
ask you a question, and I beg you to answer truthfully.

'Have you anywhere seen or heard of the daughter of an emperor, king,
or a prince, who is as clever and as handsome as I am, and who would be
worthy to be my wife and the queen of my country?'

The merchants considered for some time. At last the eldest of them said:
'I have heard that across many seas, in the Island of Busan, there is a
mighty king, whose daughter, the Princess Helena, is so lovely that she
can certainly not be plainer than your Majesty, and so clever that the
wisest greybeard cannot guess her riddles.'

'Is the island far off, and which is the way to it?'

'It is not near,' was the answer. 'The journey would take ten years, and
we do not know the way. And even if we did, what use would that be? The
princess is no bride for you.'

'How dare you say so?' cried the king angrily.

'Your Majesty must pardon us; but just think for a moment. Should you
send an envoy to the island he will take ten years to get there and ten
more to return--twenty years in all. Will not the princess have grown
old in that time and have lost all her beauty?'

The king reflected gravely. Then he thanked the merchants, gave them
leave to trade in his country without paying any duties, and dismissed
them.

After they were gone the king remained deep in thought. He felt puzzled
and anxious; so he decided to ride into the country to distract his
mind, and sent for his huntsmen and falconers. The huntsmen blew their
horns, the falconers took their hawks on their wrists, and off they all
set out across country till they came to a green hedge. On the other
side of the hedge stretched a great field of maize as far as the eye
could reach, and the yellow ears swayed to and fro in the gentle breeze
like a rippling sea of gold.

The king drew rein and admired the field. 'Upon my word,' said he,
'whoever dug and planted it must be good workmen. If all the fields in
my kingdom were as well cared for as this, there would be more bread
than my people could eat.' And he wished to know to whom the field
belonged.

Off rushed all his followers at once to do his bidding, and found a
nice, tidy farmhouse, in front of which sat seven peasants, lunching
on rye bread and drinking water. They wore red shirts bound with gold
braid, and were so much alike that one could hardly tell one from
another.

The messengers asked: 'Who owns this field of golden maize?' And the
seven brothers answered: 'The field is ours.'

'And who are you?'

'We are King Archidej's labourers.'

These answers were repeated to the king, who ordered the brothers to
be brought before him at once. On being asked who they were, the eldest
said, bowing low:

'We, King Archidej, are your labourers, children of one father and
mother, and we all have the same name, for each of us is called Simon.
Our father taught us to be true to our king, and to till the ground,
and to be kind to our neighbours. He also taught each of us a different
trade which he thought might be useful to us, and he bade us not neglect
our mother earth, which would be sure amply to repay our labour.'

The king was pleased with the honest peasant, and said: 'You have done
well, good people, in planting your field, and now you have a golden
harvest. But I should like each of you to tell me what special trades
your father taught you.'

'My trade, O king!' said the first Simon, 'is not an easy one. If you
will give me some workmen and materials I will build you a great white
pillar that shall reach far above the clouds.'

'Very good,' replied the king. 'And you, Simon the second, what is your
trade?'

'Mine, your Majesty, needs no great cleverness. When my brother has
built the pillar I can mount it, and from the top, far above the clouds,
I can see what is happening: in every country under the sun.'

'Good,' said the king; 'and Simon the third?'

'My work is very simple, sire. You have many ships built by learned men,
with all sorts of new and clever improvements. If you wish it I will
build you quite a simple boat--one, two, three, and it's done! But my
plain little home-made ship is not grand enough for a king. Where other
ships take a year, mine makes the voyage in a day, and where they would
require ten years mine will do the distance in a week.'

'Good,' said the king again; 'and what has Simon the fourth learnt?'

'My trade, O king, is really of no importance. Should my brother build
you a ship, then let me embark in it. If we should be pursued by an
enemy I can seize our boat by the prow and sink it to the bottom of the
sea. When the enemy has sailed off, I can draw it up to the top again.'

'That is very clever of you,' answered the king; 'and what does Simon
the fifth do?'

'My work, your Majesty, is mere smith's work. Order me to build a smithy
and I will make you a cross-bow, but from which neither the eagle in the
sky nor the wild beast in the forest is safe. The bolt hits whatever the
eye sees.'

'That sounds very useful,' said the king. 'And now, Simon the sixth,
tell me your trade.'

'Sire, it is so simple I am almost ashamed to mention it. If my brother
hits any creature I catch it quicker than any dog can. If it falls into
the water I pick it up out of the greatest depths, and if it is in a
dark forest I can find it even at midnight.'

The king was much pleased with the trades and talk of the six brothers,
and said: 'Thank you, good people; your father did well to teach you all
these things. Now follow me to the town, as I want to see what you can
do. I need such people as you about me; but when harvest time comes I
will send you home with royal presents.'

The brothers bowed and said: 'As the king wills.' Suddenly the king
remembered that he had not questioned the seventh Simon, so he turned to
him and said: 'Why are you silent? What is your handicraft?'

And the seventh Simon answered: 'I have no handicraft, O king; I have
learnt nothing. I could not manage it. And if I do know how to do
anything it is not what might properly be called a real trade--it is
rather a sort of performance; but it is one which no one--not the king
himself--must watch me doing, and I doubt whether this performance of
mine would please your Majesty.'

'Come, come,' cried the king; 'I will have no excuses, what is this
trade?'

'First, sire, give me your royal word that you will not kill me when I
have told you. Then you shall hear.'

'So be it, then; I give you my royal word.'

Then the seventh Simon stepped back a little, cleared his throat, and
said: 'My trade, King Archidej, is of such a kind that the man who
follows it in your kingdom generally loses his life and has no hopes of
pardon. There is only one thing I can do really well, and that is--to
steal, and to hide the smallest scrap of anything I have stolen. Not
the deepest vault, even if its lock were enchanted, could prevent my
stealing anything out of it that I wished to have.'

When the king heard this he fell into a passion. 'I will not pardon
you, you rascal,' he cried; 'I will shut you up in my deepest dungeon on
bread and water till you have forgotten such a trade. Indeed, it would
be better to put you to death at once, and I've a good mind to do so.'

'Don't kill me, O king! I am really not as bad as you think. Why, had I
chosen, I could have robbed the royal treasury, have bribed your judges
to let me off, and built a white marble palace with what was left.
But though I know how to steal I don't do it. You yourself asked me my
trade. If you kill me you will break your royal word.'

'Very well,' said the king, 'I will not kill you. I pardon you. But from
this hour you shall be shut up in a dark dungeon. Here, guards! away
with him to the prison. But you six Simons follow me and be assured of
my royal favour.'

So the six Simons followed the king. The seventh Simon was seized by the
guards, who put him in chains and threw him in prison with only bread
and water for food. Next day the king gave the first Simon carpenters,
masons, smiths and labourers, with great stores of iron, mortar, and the
like, and Simon began to build. And he built his great white pillar
far, far up into the clouds, as high as the nearest stars; but the other
stars were higher still.

Then the second Simon climbed up the pillar and saw and heard all that
was going on through the whole world. When he came down he had all sorts
of wonderful things to tell. How one king was marching in battle against
another, and which was likely to be the victor. How, in another place,
great rejoicings were going on, while in a third people were dying of
famine. In fact there was not the smallest event going on over the earth
that was hidden from him.

Next the third Simon began. He stretched out his arms, once, twice,
thrice, and the wonder-ship was ready. At a sign from the king it was
launched, and floated proudly and safely like a bird on the waves.
Instead of ropes it had wires for rigging, and musicians played on them
with fiddle bows and made lovely music. As the ship swam about, the
fourth Simon seized the prow with his strong hand, and in a moment it
was gone--sunk to the bottom of the sea. An hour passed, and then the
ship floated again, drawn up by Simon's left hand, while in his right he
brought a gigantic fish from the depth of the ocean for the royal table.

Whilst this was going on the fifth Simon had built his forge and
hammered out his iron, and when the king returned from the harbour the
magic cross-bow was made.

His Majesty went out into an open field at once, looked up into the sky
and saw, far, far away, an eagle flying up towards the sun and looking
like a little speck.

'Now,' said the king, 'if you can shoot that bird I will reward you.'

Simon only smiled; he lifted his cross-bow, took aim, fired, and the
eagle fell. As it was falling the sixth Simon ran with a dish, caught
the bird before it fell to earth and brought it to the king.

'Many thanks, my brave lads,' said the king; 'I see that each of you is
indeed a master of his trade. You shall be richly rewarded. But now rest
and have your dinner.'

The six Simons bowed and went to dinner. But they had hardly begun
before a messenger came to say that the king wanted to see them. They
obeyed at once and found him surrounded by all his court and men of
state.

'Listen, my good fellows,' cried the king, as soon as he saw them. 'Hear
what my wise counsellors have thought of. As you, Simon the second,
can see the whole world from the top of the great pillar, I want you to
climb up and to see and hear. For I am told that, far away, across many
seas, is the great kingdom of the Island of Busan, and that the daughter
of the king is the beautiful Princess Helena.'

Off ran the second Simon and clambered quickly up the pillar. He gazed
around, listened on all sides, and then slid down to report to the king.

'Sire, I have obeyed your orders. Far away I saw the Island of Busan.
The king is a mighty monarch, but full of pride, harsh and cruel. He
sits on his throne and declares that no prince or king on earth is good
enough for his lovely daughter, that he will give her to none, and
that if any king asks for her hand he will declare war against him and
destroy his kingdom.'

'Has the king of Busan a great army?' asked King Archidej; 'is his
country far off?'

'As far as I could judge,' replied Simon, 'it would take you nearly ten
years in fair weather to sail there. But if the weather were stormy
we might say twelve. I saw the army being reviewed. It is not so very
large--a hundred thousand men at arms and a hundred thousand knights.
Besides these, he has a strong bodyguard and a good many cross-bowmen.
Altogether you may say another hundred thousand, and there is a picked
body of heroes who reserve themselves for great occasions requiring
particular courage.'

The king sat for some time lost in thought. At last he said to the
nobles and courtiers standing round: 'I am determined to marry the
Princess Helena, but how shall I do it?'

The nobles, courtiers and counsellors said nothing, but tried to hide
behind each other. Then the third Simon said:

'Pardon me, your Majesty, if I offer my advice. You wish to go to the
Island of Busan? What can be easier? In my ship you will get there in a
week instead of in ten years. But ask your council to advise you what
to do when you arrive--in one word, whether you will win the princess
peacefully or by war?'

But the wise men were as silent as ever.

The king frowned, and was about to say something sharp, when the Court
Fool pushed his way to the front and said: 'Dear me, what are all you
clever people so puzzled about? The matter is quite clear. As it seems
it will not take long to reach the island why not send the seventh
Simon? He will steal the fair maiden fast enough, and then the king,
her father, may consider how he is going to bring his army over here--it
will take him ten years to do it!---no less! What do you think of my
plan?'

'What do I think? Why, that your idea is capital, and you shall be
rewarded for it. Come, guards, hurry as fast as you can and bring the
seventh Simon before me.'

Not many minutes later, Simon the seventh stood before the king, who
explained to him what he wished done, and also that to steal for the
benefit of his king and country was by no means a wrong thing, though it
was very wrong to steal for his own advantage.

The youngest Simon, who looked very pale and hungry, only nodded his
head.

'Come,' said the king, 'tell me truly. Do you think you could steal the
Princess Helena?'

'Why should I not steal her, sire? The thing is easy enough. Let my
brother's ship be laden with rich stuffs, brocades, Persian carpets,
pearls and jewels. Send me in the ship. Give me my four middle brothers
as companions, and keep the two others as hostages.'

When the king heard these words his heart became filled with longing,
and he ordered all to be done as Simon wished. Every one ran about to do
his bidding; and in next to no time the wonder-ship was laden and ready
to start.

The five Simons took leave of the king, went on board, and had no sooner
set sail than they were almost out of sight. The ship cut through the
waters like a falcon through the air, and just a week after starting
sighted the Island of Busan. The coast appeared to be strongly guarded,
and from afar the watchman on a high tower called out: 'Halt and anchor!
Who are you? Where do you come from, and what do you want?'

The seventh Simon answered from the ship: 'We are peaceful people. We
come from the country of the great and good King Archidej, and we bring
foreign wares--rich brocades, carpets, and costly jewels, which we wish
to show to your king and the princess. We desire to trade--to sell, to
buy, and to exchange.'

The brothers launched a small boat, took some of their valuable goods
with them, rowed to shore and went up to the palace. The princess sat
in a rose-red room, and when she saw the brothers coming near she called
her nurse and other women, and told them to inquire who and what these
people were, and what they wanted.

The seventh Simon answered the nurse: 'We come from the country of the
wise and good King Archidej,' said he, 'and we have brought all sorts
of goods for sale. We trust the king of this country may condescend
to welcome us, and to let his servants take charge of our wares. If he
considers them worthy to adorn his followers we shall be content.'

This speech was repeated to the princess, who ordered the brothers to
be brought to the red-room at once. They bowed respectfully to her and
displayed some splendid velvets and brocades, and opened cases of pearls
and precious stones. Such beautiful things had never been seen in the
island, and the nurse and waiting women stood bewildered by all the
magnificence. They whispered together that they had never beheld
anything like it. The princess too saw and wondered, and her eyes could
not weary of looking at the lovely things, or her fingers of stroking
the rich soft stuffs, and of holding up the sparkling jewels to the
light.

'Fairest of princesses,' said Simon. 'Be pleased to order your
waiting-maids to accept the silks and velvets, and let your women trim
their head-dresses with the jewels; these are no special treasures.
But permit me to say that they are as nothing to the many coloured
tapestries, the gorgeous stones and ropes of pearls in our ship. We did
not like to bring more with us, not knowing what your royal taste might
be; but if it seems good to you to honour our ship with a visit, you
might condescend to choose such things as were pleasing in your eyes.'

This polite speech pleased the princess very much. She went to the
king and said: 'Dear father, some merchants have arrived with the most
splendid wares. Pray allow me to go to their ship and choose out what I
like.'

The king thought and thought, frowned hard and rubbed his ear. At last
he gave consent, and ordered out his royal yacht, with 100 cross-bows,
100 knights, and 1,000 soldiers, to escort the Princess Helena.

Off sailed the yacht with the princess and her escort. The brothers
Simon came on board to conduct the princess to their ship, and, led by
the brothers and followed by her nurse and other women, she crossed the
crystal plank from one vessel to another.

The seventh Simon spread out his goods, and had so many curious
and interesting tales to tell about them, that the princess forgot
everything else in looking and listening, so that she did not know that
the fourth Simon had seized the prow of the ship, and that all of a
sudden it had vanished from sight, and was racing along in the depths of
the sea.

The crew of the royal yacht shouted aloud, the knights stood still with
terror, the soldiers were struck dumb and hung their heads. There was
nothing to be done but to sail back and tell the king of his loss.

How he wept and stormed! 'Oh, light of my eyes,' he sobbed; 'I am indeed
punished for my pride. I thought no one good enough to be your husband,
and now you are lost in the depths of the sea, and have left me alone!
As for all of you who saw this thing--away with you! Let them be put in
irons and lock them up in prison, whilst I think how I can best put them
to death!'

Whilst the King of Busan was raging and lamenting in this fashion,
Simon's ship was swimming like any fish under the sea, and when the
island was well out of sight he brought it up to the surface again. At
that moment the princess recollected herself. 'Nurse,' said she, 'we
have been gazing at these wonders only too long. I hope my father won't
be vexed at our delay.'

She tore herself away and stepped on deck. Neither the yacht nor the
island was in sight! Helena wrung her hands and beat her breast. Then
she changed herself into a white swan and flew off. But the fifth Simon
seized his bow and shot the swan, and the sixth Simon did not let it
fall into the water but caught it in the ship, and the swan turned into
a silver fish, but Simon lost no time and caught the fish, when, quick
as thought, the fish turned into a black mouse and ran about the ship.
It darted towards a hole, but before it could reach it Simon sprang upon
it more swiftly than any cat, and then the little mouse turned once more
into the beautiful Princess Helena.

Early one morning King Archidej sat thoughtfully at his window gazing
out to sea. His heart was sad and he would neither eat nor drink. His
thoughts were full of the Princess Helena, who was as lovely as a dream.
Is that a white gull he sees flying towards the shore, or is it a sail?
No, it is no gull, it is the wonder-ship flying along with billowing
sails. Its flags wave, the fiddlers play on the wire rigging, the anchor
is thrown out and the crystal plank laid from the ship to the pier. The
lovely Helena steps across the plank. She shines like the sun, and the
stars of heaven seem to sparkle in her eyes.

Up sprang King Archidej in haste: 'Hurry, hurry,' he cried. 'Let us
hasten to meet her! Let the bugles sound and the joy bells be rung!'

And the whole Court swarmed with courtiers and servants. Golden carpets
were laid down and the great gates thrown open to welcome the princess.

King Archidej went out himself, took her by the hand and led her into
the royal apartments.

'Madam,' said he, 'the fame of your beauty had reached me, but I had not
dared to expect such loveliness. Still I will not keep you here against
your will. If you wish it, the wonder-ship shall take you back to your
father and your own country; but if you will consent to stay here, then
reign over me and my country as our queen.'

What more is there to tell? It is not hard to guess that the princess
listened to the king's wooing, and their betrothal took place with great
pomp and rejoicings.

The brothers Simon were sent again to the Island of Busan with a letter
to the king from his daughter to invite him to their wedding. And the
wonder-ship arrived at the Island of Busan just as all the knights and
soldiers who had escorted the princess were being led out to execution.

Then the seventh Simon cried out from the ship: 'Stop! stop! I bring a
letter from the Princess Helena!'

The King of Busan read the letter over and over again, and ordered the
knights and soldiers to be set free. He entertained King Archidej's
ambassadors hospitably, and sent his blessing to his daughter, but he
could not be brought to attend the wedding.

When the wonder-ship got home King Archidej and Princess Helena were
enchanted with the news it brought.

The king sent for the seven Simons. 'A thousand thanks to you, my brave
fellows,' he cried. 'Take what gold, silver, and precious stones you
will out of my treasury. Tell me if there is anything else you wish for
and I will give it you, my good friends. Do you wish to be made nobles,
or to govern towns? Only speak.'

Then the eldest Simon bowed and said: 'We are plain folk, your Majesty,
and understand simple things best. What figures should we cut as nobles
or governors? Nor do we desire gold. We have our fields which give us
food, and as much money as we need. If you wish to reward us then grant
that our land may be free of taxes, and of your goodness pardon the
seventh Simon. He is not the first who has been a thief by trade and he
will certainly not be the last.'

'So be it,' said the king; 'your land shall be free of all taxes, and
Simon the seventh is pardoned.'

Then the king gave each brother a goblet of wine and invited them to the
wedding feast. And what a feast that was!"""
)

"""**STORY 4**

"""

t = [
    ("Who was King Archidej and what made his life seemingly perfect?", "King Archidej was a wealthy and handsome ruler who commanded a great army and ruled over many cities. His life seemed perfect because he had everything—luxurious palaces, a wise council, and power—but he was unhappy because he couldn’t find a bride to his liking."),
    ("What news did the merchants bring to King Archidej?", "The merchants told King Archidej about Princess Helena of the Island of Busan, who was extremely beautiful and intelligent, and could match the king in both traits."),
    ("Why did the merchants discourage the king from pursuing Princess Helena?", "They said the island was so far away that it would take ten years to reach and another ten to return. By the time an envoy came back, the princess might have aged and lost her beauty."),
    ("Who were the Seven Simons?", "The Seven Simons were seven peasant brothers, all with the same name (Simon), who were skilled in different trades, taught by their father to be hard-working, honest, and kind."),
    ("What was the first Simon’s special trade?", "The first Simon could build a tall white pillar that reached far above the clouds."),
    ("What ability did the second Simon possess?", "He could climb the pillar and see everything happening in the world from its top, even across great distances."),
    ("What was unique about the third Simon’s ship?", "His homemade ship could travel incredibly fast—covering distances in a week that would normally take ten years."),
    ("How did the fourth Simon contribute to their missions?", "He could sink their ship underwater to avoid enemies and raise it again once the danger passed."),
    ("Why was the seventh Simon imprisoned?", "The seventh Simon admitted that his only skill was stealing and hiding things so well that even enchanted vaults couldn't stop him. Though he claimed not to misuse his talent, the king imprisoned him for it."),
    ("What did the king do after learning the skills of the six Simons?", "He rewarded them with his royal favor, tested their abilities, and allowed them to serve him, especially since their skills could help in his quest to win Princess Helena.")
]


s.append(t)

story.append("""
Lucky Luck

Once upon a time there was a king who had an only son. When the lad was
about eighteen years old his father had to go to fight in a war against
a neighbouring country, and the king led his troops in person. He bade
his son act as Regent in his absence, but ordered him on no account to
marry till his return.

Time went by. The prince ruled the country and never even thought of
marrying. But when he reached his twenty-fifth birthday he began to
think that it might be rather nice to have a wife, and he thought so
much that at last he got quite eager about it. He remembered, however,
what his father had said, and waited some time longer, till at last it
was ten years since the king went out to war. Then the prince called his
courtiers about him and set off with a great retinue to seek a bride. He
hardly knew which way to go, so he wandered about for twenty days, when,
suddenly, he found himself in his father's camp.

The king was delighted to see his son, and had a great many questions
to ask and answer; but when he heard that instead of quietly waiting
for him at home the prince was starting off to seek a wife he was very
angry, and said: 'You may go where you please but I will not leave any
of my people with you.'

Only one faithful servant stayed with the prince and refused to part
from him. They journeyed over hill and dale till they came to a place
called Goldtown. The King of Goldtown had a lovely daughter, and the
prince, who soon heard about her beauty, could not rest till he saw her.

He was very kindly received, for he was extremely good-looking and had
charming manners, so he lost no time in asking for her hand and her
parents gave her to him with joy. The wedding took place at once, and
the feasting and rejoicings went on for a whole month. At the end of
the month they set off for home, but as the journey was a long one they
spent the first evening at an inn. Everyone in the house slept, and only
the faithful servant kept watch. About midnight he heard three crows,
who had flown to the roof, talking together.

'That's a handsome couple which arrived here tonight. It seems quite a
pity they should lose their lives so soon.'

'Truly,' said the second crow; 'for to-morrow, when midday strikes, the
bridge over the Gold Stream will break just as they are driving over
it. But, listen! whoever overhears and tells what we have said will be
turned to stone up to his knees.'

The crows had hardly done speaking when away they flew. And close upon
them followed three pigeons.

'Even if the prince and princess get safe over the bridge they will
perish,' said they; 'for the king is going to send a carriage to meet
them which looks as new as paint. But when they are seated in it a
raging wind will rise and whirl the carriage away into the clouds. Then
it will fall suddenly to earth, and they will be killed. But anyone who
hears and betrays what we have said will be turned to stone up to his
waist.'

With that the pigeons flew off and three eagles took their places, and
this is what they said:

'If the young couple does manage to escape the dangers of the bridge
and the carriage, the king means to send them each a splendid gold
embroidered robe. When they put these on they will be burnt up at once.
But whoever hears and repeats this will turn to stone from head to
foot.'

Early next morning the travellers got up and breakfasted. They began to
tell each other their dreams. At last the servant said:

'Gracious prince, I dreamt that if your Royal Highness would grant all
I asked we should get home safe and sound; but if you did not we should
certainly be lost. My dreams never deceive me, so I entreat you to
follow my advice during the rest of the journey.'

'Don't make such a fuss about a dream,' said the prince; 'dreams are but
clouds. Still, to prevent your being anxious I will promise to do as you
wish.'

With that they set out on their journey.

At midday they reached the Gold Stream. When they got to the bridge the
servant said: 'Let us leave the carriage here, my prince, and walk
a little way. The town is not far off and we can easily get another
carriage there, for the wheels of this one are bad and will not hold out
much longer.'

The prince looked well at the carriage. He did not think it looked so
unsafe as his servant said; but he had given his word and he held to it.

They got down and loaded the horses with the luggage. The prince and
his bride walked over the bridge, but the servant said he would ride the
horses through the stream so as to water and bathe them.

They reached the other side without harm, and bought a new carriage in
the town, which was quite near, and set off once more on their travels;
but they had not gone far when they met a messenger from the king who
said to the prince: 'His Majesty has sent your Royal Highness this
beautiful carriage so that you may make a fitting entry into your own
country and amongst your own people.'

The prince was so delighted that he could not speak. But the servant
said: 'My lord, let me examine this carriage first and then you can get
in if I find it is all right; otherwise we had better stay in our own.'

The prince made no objections, and after looking the carriage well
over the servant said: 'It is as bad as it is smart'; and with that
he knocked it all to pieces, and they went on in the one that they had
bought.

At last they reached the frontier; there another messenger was waiting
for them, who said that the king had sent two splendid robes for the
prince and his bride, and begged that they would wear them for their
state entry. But the servant implored the prince to have nothing to do
with them, and never gave him any peace till he had obtained leave to
destroy the robes.

The old king was furious when he found that all his arts had failed;
that his son still lived and that he would have to give up the crown to
him now he was married, for that was the law of the land. He longed to
know how the prince had escaped, and said: 'My dear son, I do indeed
rejoice to have you safely back, but I cannot imagine why the beautiful
carriage and the splendid robes I sent did not please you; why you had
them destroyed.'

'Indeed, sire,' said the prince, 'I was myself much annoyed at their
destruction; but my servant had begged to direct everything on the
journey and I had promised him that he should do so. He declared that we
could not possibly get home safely unless I did as he told me.'

The old king fell into a tremendous rage. He called his Council together
and condemned the servant to death.

The gallows was put up in the square in front of the palace. The servant
was led out and his sentence read to him.

The rope was being placed round his neck, when he begged to be allowed
a few last words. 'On our journey home,' he said, 'we spent the first
night at an inn. I did not sleep but kept watch all night.' And then he
went on to tell what the crows had said, and as he spoke he turned to
stone up to his knees. The prince called to him to say no more as he had
proved his innocence. But the servant paid no heed to him, and by the
time his story was done he had turned to stone from head to foot.

Oh! how grieved the prince was to lose his faithful servant! And what
pained him most was the thought that he was lost through his very
faithfulness, and he determined to travel all over the world and never
rest till he found some means of restoring him to life.

Now there lived at Court an old woman who had been the prince's nurse.
To her he confided all his plans, and left his wife, the princess, in
her care. 'You have a long way before you, my son,' said the old woman;
'you must never return till you have met with Lucky Luck. If he cannot
help you no one on earth can.'

So the prince set off to try to find Lucky Luck. He walked and walked
till he got beyond his own country, and he wandered through a wood for
three days but did not meet a living being in it. At the end of the
third day he came to a river near which stood a large mill. Here he
spent the night. When he was leaving next morning the miller asked him:
'My gracious lord, where are you going all alone?'

And the prince told him.

'Then I beg your Highness to ask Lucky Luck this question: Why is it
that though I have an excellent mill, with all its machinery complete,
and get plenty of grain to grind, I am so poor that I hardly know how to
live from one day to another?'

The prince promised to inquire, and went on his way. He wandered about
for three days more, and at the end of the third day saw a little town.
It was quite late when he reached it, but he could discover no light
anywhere, and walked almost right through it without finding a house
where he could turn in. But far away at the end of the town he saw a
light in a window. He went straight to it and in the house were three
girls playing a game together. The prince asked for a night's lodging
and they took him in, gave him some supper and got a room ready for him,
where he slept.

Next morning when he was leaving they asked where he was going and he
told them his story. 'Gracious prince,' said the maidens, 'do ask Lucky
Luck how it happens that here we are over thirty years old and no lover
has come to woo us, though we are good, pretty, and very industrious.'

The prince promised to inquire, and went on his way.

Then he came to a great forest and wandered about in it from morning to
night and from night to morning before he got near the other end. Here
he found a pretty stream which was different from other streams as,
instead of flowing, it stood still and began to talk: 'Sir prince, tell
me what brings you into these wilds? I must have been flowing here a
hundred years and more and no one has ever yet come by.'

'I will tell you,' answered the prince, 'if you will divide yourself so
that I may walk through.'

The stream parted at once, and the prince walked through without wetting
his feet; and directly he got to the other side he told his story as he
had promised.

'Oh, do ask Lucky Luck,' cried the brook, 'why, though I am such a
clear, bright, rapid stream I never have a fish or any other living
creature in my waters.'

The prince said he would do so, and continued his journey.

When he got quite clear of the forest he walked on through a lovely
valley till he reached a little house thatched with rushes, and he went
in to rest for he was very tired.

Everything in the house was beautifully clean and tidy, and a cheerful
honest-looking old woman was sitting by the fire.

'Good-morning, mother,' said the prince.

'May Luck be with you, my son. What brings you into these parts?'

'I am looking for Lucky Luck,' replied the prince.

'Then you have come to the right place, my son, for I am his mother. He
is not at home just now, he is out digging in the vineyard. Do you go
too. Here are two spades. When you find him begin to dig, but don't
speak a word to him. It is now eleven o'clock. When he sits down to
eat his dinner sit beside him and eat with him. After dinner he will
question you, and then tell him all your troubles freely. He will answer
whatever you may ask.'

With that she showed him the way, and the prince went and did just as
she had told him. After dinner they lay down to rest.

All of a sudden Lucky Luck began to speak and said: 'Tell me, what sort
of man are you, for since you came here you have not spoken a word?'

'I am not dumb,' replied the young man, 'but I am that unhappy prince
whose faithful servant has been turned to stone, and I want to know how
to help him.'

'And you do well, for he deserves everything. Go back, and when you
get home your wife will just have had a little boy. Take three drops of
blood from the child's little finger, rub them on your servant's wrists
with a blade of grass and he will return to life.'

'I have another thing to ask,' said the prince, when he had thanked him.
'In the forest near here is a fine stream but not a fish or other living
creature in it. Why is this?'

'Because no one has ever been drowned in the stream. But take care, in
crossing, to get as near the other side as you can before you say so, or
you may be the first victim yourself.'

'Another question, please, before I go. On my way here I lodged
one night in the house of three maidens. All were well-mannered,
hard-working, and pretty, and yet none has had a wooer. Why was this?'

'Because they always throw out their sweepings in the face of the sun.'

'And why is it that a miller, who has a large mill with all the best
machinery and gets plenty of corn to grind is so poor that he can hardly
live from day to day?'

'Because the miller keeps everything for himself, and does not give to
those who need it.'

The prince wrote down the answers to his questions, took a friendly
leave of Lucky Luck, and set off for home.

When he reached the stream it asked if he brought it any good news.
'When I get across I will tell you,' said he. So the stream parted; he
walked through and on to the highest part of the bank. He stopped and
shouted out:

'Listen, oh stream! Lucky Luck says you will never have any living
creature in your waters until someone is drowned in you.'

The words were hardly out of his mouth when the stream swelled and
overflowed till it reached the rock up which he had climbed, and dashed
so far up it that the spray flew over him. But he clung on tight, and
after failing to reach him three times the stream returned to its proper
course. Then the prince climbed down, dried himself in the sun, and set
out on his march home.

He spent the night once more at the mill and gave the miller his answer,
and by-and-by he told the three sisters not to throw out all their
sweepings in the face of the sun.

The prince had hardly arrived at home when some thieves tried to ford
the stream with a fine horse they had stolen. When they were half-way
across, the stream rose so suddenly that it swept them all away. From
that time it became the best fishing stream in the country-side.

The miller, too, began to give alms and became a very good man, and in
time grew so rich that he hardly knew how much he had.

And the three sisters, now that they no longer insulted the sun, had
each a wooer within a week.

When the prince got home he found that his wife had just got a fine
little boy. He did not lose a moment in pricking the baby's finger till
the blood ran, and he brushed it on the wrists of the stone figure,
which shuddered all over and split with a loud noise in seven parts and
there was the faithful servant alive and well.

When the old king saw this he foamed with rage, stared wildly about,
flung himself on the ground and died.

The servant stayed on with his royal master and served him faithfully
all the rest of his life; and, if neither of them is dead, he is serving
him still.""")

t = [
    ("Why did the prince decide to leave home and search for a bride after ten years?", "Although his father explicitly ordered him not to marry until the war was over, the prince grew restless and lonely by his twenty-fifth birthday—ten years after his father left—and became eager for companionship, prompting him to break his father’s command and seek a wife."),
    ("What prophecy did the three crows reveal at the inn, and what was the penalty for revealing it?", "The three crows foretold that when the couple crossed the bridge over the Gold Stream at noon the next day, it would collapse under them. They also warned that anyone who repeated their secret would be turned to stone up to the knees."),
    ("How did the servant’s interpretation of his dream influence the prince’s decisions?", "The servant convinced the prince to heed his warning that following the servant’s advice would ensure their safety. Trusting his dream, the prince agreed to leave the carriage and walk, thus avoiding the bridge collapse."),
    ("What three dangers did the royal couple face on their journey home, and how did they escape each one?", "- **Bridge collapse** at the Gold Stream (crows’ warning): they walked instead of riding in the carriage. \n   - **Whirlwind carriage ride** (pigeons’ warning): they refused the king’s fancy carriage and destroyed it at the servant’s insistence. \n   - **Burning robes** (eagles’ warning): they destroyed the king’s gold-embroidered robes rather than wear them."),
    ("Why did the servant insist on examining and ultimately destroying each carriage the king sent?", "Because each gift—first the carriage, then the second one—was cursed to kill the prince and princess as foretold by the pigeons, and the servant’s careful inspection and destruction of the doomed carriages saved their lives."),
    ("What led the king to condemn the faithful servant to death, despite the servant’s proven loyalty?", "The king, ignorant of the servant’s heroism, believed the servant’s destruction of his gifts was deliberate defiance rather than life-saving precaution, so he turned against him and sentenced him to death for disobeying royal commands."),
    ("How was the servant’s final confession both his salvation and his downfall?", "When the servant revealed the truth about the crows’ prophecy to prove his innocence, he triggered the curse on anyone who disclosed the secret, turning himself first to stone to the knees and then completely to stone."),
    ("Who or what ultimately pointed the prince to Lucky Luck, and what tasks did Lucky Luck set before him?", "The prince’s old nurse, still at court, directed him to seek Lucky Luck. Lucky Luck’s mother advised the prince to find her son digging in the vineyard, work silently beside him, and then freely recount his plight so Lucky Luck could offer answers."),
    ("What answers did Lucky Luck provide to the prince’s four questions (about the miller, the maidens, the fishless stream, and reviving the servant)?", "- **Miller’s poverty:** He hoarded all his grain and gave nothing to the poor. \n   - **Maiden’s unmarried state:** They tossed their household sweepings into the sun’s face, offending it. \n   - **Fishless stream:** No one had ever drowned there. \n   - **Reviving the servant:** Rub three drops of the newborn prince’s finger blood on the stone servant’s wrists with a blade of grass."),
    ("What moral lessons about obedience, trust, and fortune does the tale of Lucky Luck convey?", "The story teaches that blind disobedience can be dangerous, that wise counsel and faithfulness save lives, and that true 'luck' comes to those who help others, act generously, and heed good advice.")
]


s.append(t)

"""**STORY 5**"""

story.append("""The Hairy Man

Somewhere or other, but I don't know where, there lived a king who owned
two remarkably fine fields of rape, but every night two of the rape
heaps were burnt down in one of the fields. The king was extremely angry
at this, and sent out soldiers to catch whoever had set fire to the
ricks; but it was all of no use--not a soul could they see. Then he
offered nine hundred crowns to anyone who caught the evil-doer, and at
the same time ordered that whoever did not keep proper watch over the
fields should be killed; but though there were a great many people, none
seemed able to protect the fields.

The king had already put ninety-nine people to death, when a little
swineherd came to him who had two dogs; one was called 'Psst,' and the
other 'Hush'; and the boy told the king that he would watch over the
ricks.

When it grew dark he climbed up on the top of the fourth rick, from
where he could see the whole field. About eleven o'clock he thought he
saw someone going to a rick and putting a light to it. 'Just you wait,'
thought he, and called out to his dogs: 'Hi! Psst, Hush, catch him!'
But Psst and Hush had not waited for orders, and in five minutes the man
was caught.

Next morning he was brought bound before the king, who was so pleased
with the boy that he gave him a thousand crowns at once. The prisoner
was all covered with hair, almost like an animal; and altogether he was
so curious to look at that the king locked him up in a strong room and
sent out letters of invitation to all the other kings and princes asking
them to come and see this wonder.

That was all very well; but the king had a little boy of ten years old
who went to look at the hairy man also, and the man begged so hard to be
set free that the boy took pity on him. He stole the key of the strong
room from his mother and opened the door. Then he took the key back, but
the hairy man escaped and went off into the world.

Then the kings and princes began to arrive one after another, and all
were most anxious to see the hairy man; but he was gone! The king nearly
burst with rage and with the shame he felt. He questioned his wife
sharply, and told her that if she could not find and bring back the
hairy man he would put her in a hut made of rushes and burn her there.
The queen declared she had had nothing to do with the matter; if her son
had happened to take the key it had not been with her knowledge.

So they fetched the little prince and asked him all sorts of questions,
and at last he owned that he had let the hairy man out. The king ordered
his servants to take the boy into the forest and to kill him there, and
to bring back part of his liver and lungs.

There was grief all over the palace when the king's command was known,
for he was a great favourite. But there was no help for it, and they
took the boy out into the forest. But the man was sorry for him, and
shot a dog and carried pieces of his lungs and liver to the king, who
was satisfied, and did not trouble himself any more.

The prince wandered about in the forest and lived as best he could for
five years. One day he came upon a poor little cottage in which was an
old man. They began to talk, and the prince told his story and sad fate.
Then they recognised each other, for the old fellow was no other than
the hairy man whom the prince had set free, and who had lived ever since
in the forest.

The prince stayed here for two years; then he wished to go further. The
old man begged him hard to stay, but he would not, so his hairy friend
gave him a golden apple out of which came a horse with a golden mane,
and a golden staff with which to guide the horse. The old man also gave
him a silver apple out of which came the most beautiful hussars and a
silver staff; and a copper apple from which he could draw as many foot
soldiers as ever he wished, and a copper staff. He made the prince swear
solemnly to take the greatest care of these presents, and then he let
him go.

The boy wandered on and on till he came to a large town. Here he took
service in the king's palace, and as no one troubled themselves about
him he lived quietly on.

One day news was brought to the king that he must go out to war. He was
horribly frightened for he had a very small army, but he had to go all
the same.

When they had all left, the prince said to the housekeeper:

'Give me leave to go to the next village--I owe a small bill there, and
I want to go and pay it'; and as there was nothing to be done in the
palace the housekeeper gave him leave.

When he got beyond the town he took out his golden apple, and when the
horse sprang out he swung himself into the saddle. Then he took the
silver and the copper apples, and with all these fine soldiers he joined
the king's army.

The king saw them approach with fear in his heart, for he did not know
if it might not be an enemy; but the prince rode up, and bowed low
before him. 'I bring your Majesty reinforcements,' said he.

The king was delighted, and all dread of his enemy at once disappeared.
The princesses were there too, and they were very friendly with the
prince and begged him to get into their carriage so as to talk to them.
But he declined, and remained on horseback, as he did not know at what
moment the battle might begin; and whilst they were all talking together
the youngest princess, who was also the loveliest, took off her ring,
and her sister tore her handkerchief in two pieces, and they gave these
gifts to the prince.

Suddenly the enemy came in sight. The king asked whether his army or the
prince's should lead the way; but the prince set off first and with his
hussars he fought so bravely that only two of the enemy were left alive,
and these two were only spared to act as messengers.

The king was overjoyed and so were his daughters at this brilliant
victory. As they drove home they begged the prince to join them, but he
would not come, and galloped off with his hussars.

When he got near the town he packed his soldiers and his fine horse all
carefully into the apple again, and then strolled into the town. On his
return to the palace he was well scolded by the housekeeper for staying
away so long.if os.path.isfile(str(qa_data_json)):
    print(f"{qa_data_json} exists.")
else:
    print(f"{qa_data_json} does not exist.")


Well, the whole matter might have ended there; but it so happened that
the younger princess had fallen in love with the prince, as he had with
her. And as he had no jewels with him, he gave her the copper apple and
staff.

One day, as the princesses were talking with their father, the younger
one asked him whether it might not have been their servant who had
helped him so much. The king was quite angry at the idea; but, to
satisfy her, he ordered the servant's room to be searched. And there,
to everyone's surprise, they found the golden ring and the half of the
handkerchief. When these were brought to the king he sent for the prince
at once and asked if it had been he who had come to their rescue.

'Yes, your Majesty, it was I,' answered the prince.

'But where did you get your army?'

'If you wish to see it, I can show it you outside the city walls.'

And so he did; but first he asked for the copper apple from the younger
princess, and when all the soldiers were drawn up there were such
numbers that there was barely room for them.

The king gave him his daughter and kingdom as a reward for his aid, and
when he heard that the prince was himself a king's son his joy knew no
bounds. The prince packed all his soldiers carefully up once more, and
they went back into the town.

Not long after there was a grand wedding; perhaps they may all be alive
still, but I don't know.
""")

t=[
    ("Why did the king set a reward of 900 crowns and threaten execution for failure to guard the rapeseed fields?", "Each night two heaps in his fine rapeseed fields were mysteriously burned, so he offered 900 crowns to anyone who caught the culprit and decreed that any guard who failed would be executed, hoping to deter further fires and ensure vigilance."),
    ("Who volunteered to watch the fields, and how did he manage to capture the arsonist?", "A humble swineherd with two dogs—Psst and Hush—offered to stand watch. He climbed atop a rick, watched through the night, and at around eleven o’clock called his dogs to seize the hairy man as he set fire to a heap."),
    ("What was the hairy man’s appearance, and what did the king do with him upon capture?", "The prisoner was covered head-to-foot in coarse hair like an animal. The king locked him in a strong room as a curiosity and summoned neighboring rulers to view this wonder."),
    ("How did the young prince free the hairy man, and what were the immediate consequences?", "Moved by compassion, the ten-year-old prince stole his mother’s key to unlock the strong room and released the hairy man, who then escaped. In anger, the king ordered that the prince be taken into the forest and killed, demanding proof by bringing back part of his liver and lungs."),
    ("Who intervened to save the prince from execution, and how was he rescued?", "The hairy man, hidden in the woods, shot the hound assigned to kill the boy. He brought pieces of the dog’s liver and lungs to the king, who, believing them to be the prince’s, spared the child’s life."),
    ("How did the prince eventually reunite with the hairy man after years in the forest?", "After wandering alone for five years, the prince encountered a poor old man in a cottage, who was revealed to be the hairy man in disguise when the prince recounted his story, and the two recognized each other."),
    ("What magical gifts did the hairy man bestow upon the prince, and what powers did they hold?", "He gave three enchanted apples and matching staffs: \n   - **Golden apple & staff:** summoned a golden-maned horse. \n   - **Silver apple & staff:** produced a regiment of splendid hussars. \n   - **Copper apple & staff:** yielded an unlimited army of foot soldiers."),
    ("How did the prince use these gifts to aid a besieged king?", "When his host king faced a powerful enemy, the prince released his golden horse and troops to reinforce the royal army. He led the hussars to a decisive victory, saving the kingdom."),
    ("How did the king’s youngest princess recognize the prince’s true identity, and what tokens did she provide?", "During court festivities, she and her sister offered him gifts—the younger princess gave her ring, and the elder sister a torn half of her handkerchief—both of which were later found in the prince’s quarters, revealing his deeds."),
    ("What was the outcome for the prince, and what moral does the tale impart?", "The king rewarded the prince with his daughter’s hand and half the kingdom upon learning his valor and noble birth. The story illustrates that compassion and loyalty are repaid, and that true worth emerges through kindness and courage.")
]
s.append(t)

# print(s)
all_qa_dicts = []

for i in range(len(story)):
    story_context = story[i]
    qa_tuples = s[i]
    for question, answer in qa_tuples:
        qa_dict = {
            "context": story_context,
            "question": question,
            "answer": answer
        }
        all_qa_dicts.append(qa_dict)

# print(all_qa_dicts)

# for j in s:
#   for k in range(10):
#     print(j[0][k],"\t\t\t",j[1][k],"\n")


# flat_qa_list = []
# for context, qs, ans in qa_list:
#         for q, a in zip(qs, ans):
#             flat_qa_list.append((context, q, a))

qa_dict = all_qa_dicts

print("Total QA items:", len(qa_dict))
    # → Total QA items: 50

print(qa_dict[0])
import os
import json
import torch
import torch.nn as nn
from torch.nn import functional as F
from torch.utils.data import Dataset, DataLoader
from tokenizers import Tokenizer, models, pre_tokenizers, trainers
from pathlib import Path
from tqdm import tqdm

# Hyperparameters
pretrain_batch_size = 16
pretrain_block_size = 64
pretrain_lr = 3e-4
pretrain_epochs = 5
finetune_batch_size = 16
finetune_block_size = 64
finetune_lr = 2e-5
finetune_epochs = 3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
n_embd = 256
n_head = 3
n_layer = 4
dropout = 0.2
bpe_vocab = 30000

# Paths
file_path = Path('/home/susmita-roy/Downloads/NLP/NLP Project/')
raw_text_path = file_path / 'fairytales.txt'
checkpoint_base = file_path / 'gpt_base.pt'
checkpoint_latest = file_path / 'checkpoint_latest.pt'
qa_data_json = file_path / 'qa_data.json'

with open(qa_data_json, 'w', encoding='utf-8') as f:
    json.dump(qa_dict, f, ensure_ascii=False, indent=2)
tokenizer_path = file_path / 'tokenizer.json'

print(f"Running on device: {device}")

# Initialize tokenizer
if not os.path.isfile(tokenizer_path):
    with open('data.txt', 'w', encoding='utf-8') as f:
        f.write(open(raw_text_path, 'r', encoding='utf-8').read())
    tokenizer = Tokenizer(models.BPE())
    tokenizer.pre_tokenizer = pre_tokenizers.Whitespace()
    trainer = trainers.BpeTrainer(
        vocab_size=bpe_vocab,
        special_tokens=["<pad>", "<unk>", "[CONTEXT]", "[QUESTION]", "[ANSWER]"]
    )
    tokenizer.train(files=['data.txt'], trainer=trainer)
    tokenizer.save(str(tokenizer_path))
else:
    tokenizer = Tokenizer.from_file(str(tokenizer_path))

encode = lambda s: tokenizer.encode(s).ids
decode = lambda ids: tokenizer.decode(ids)
vocab_size = tokenizer.get_vocab_size()
# 2. Model definition
class Head(nn.Module):
    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(pretrain_block_size, pretrain_block_size)))
        self.dropout = nn.Dropout(dropout)
    def forward(self, x):
        B,T,C = x.size()
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2,-1) * (k.shape[-1] ** -0.5)
        wei = wei.masked_fill(self.tril[:T,:T]==0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        v = self.value(x)
        return wei @ v

class MultiHeadAttention(nn.Module):
    def __init__(self):
        super().__init__()
        head_size = n_embd // n_head
        self.heads = nn.ModuleList([Head(head_size) for _ in range(n_head)])
        self.proj  = nn.Linear(head_size * n_head, n_embd)
        self.dropout = nn.Dropout(dropout)
    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        return self.dropout(self.proj(out))

class FeedForward(nn.Module):
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4*n_embd), nn.ReLU(),
            nn.Linear(4*n_embd, n_embd), nn.Dropout(dropout)
        )
    def forward(self, x): return self.net(x)

class Block(nn.Module):
    def __init__(self):
        super().__init__()
        self.sa   = MultiHeadAttention()
        self.ffwd = FeedForward()
        self.ln1  = nn.LayerNorm(n_embd)
        self.ln2  = nn.LayerNorm(n_embd)
    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# Model definition (same as before)
class GPTLanguageModel(nn.Module):
    def __init__(self, block_size):
        super().__init__()
        self.token_emb = nn.Embedding(vocab_size, n_embd)
        self.pos_emb = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block() for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)
        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            nn.init.normal_(m.weight, 0.02)
            if m.bias is not None:
                m.bias.data.zero_()
        if isinstance(m, nn.Embedding):
            nn.init.normal_(m.weight, 0.02)

    def forward(self, idx, targets=None):
        B, T = idx.size()
        tok = self.token_emb(idx)
        pos = self.pos_emb(torch.arange(T, device=device))
        x = tok + pos
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)
        if targets is None:
            return logits, None
        loss = F.cross_entropy(logits.view(-1, logits.size(-1)), targets.view(-1))
        return logits, loss

    @torch.no_grad()
    def generate(self, idx, max_new_tokens, temperature=1.0, top_k=None):
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -self.pos_emb.num_embeddings:]
            logits, _ = self(idx_cond)
            logits = logits[:, -1, :] / temperature

            if top_k is not None:
                v, _ = torch.topk(logits, top_k)
                logits[logits < v[:, [-1]]] = -float('Inf')

            probs = F.softmax(logits, dim=-1)
            idx_next = torch.multinomial(probs, num_samples=1)
            idx = torch.cat([idx, idx_next], dim=1)
        return idx


# Dataset classes
class PretrainDataset(Dataset):
    def __init__(self, data, block_size):
        self.data = data
        self.block_size = block_size

    def __len__(self):
        return len(self.data) - self.block_size

    def __getitem__(self, idx):
        x = self.data[idx: idx + self.block_size]
        y = self.data[idx + 1: idx + 1 + self.block_size]
        return x, y


class QADataset(Dataset):
    def __init__(self, items, block_size=finetune_block_size, pad_id=0):
        self.items = items
        self.bs = block_size
        self.pad = pad_id

    def __len__(self):
        return len(self.items)

    def __getitem__(self, i):
        it = self.items[i]
        # Format with special tokens
        prompt = f"[CONTEXT] {it['context']} [QUESTION] {it['question']} [ANSWER]"
        answer = it['answer']

        x_ids = encode(prompt)[-self.bs:]
        y_ids = encode(answer)[:self.bs]

        # Padding
        x_ids = [self.pad] * (self.bs - len(x_ids)) + x_ids
        y_ids = y_ids + [self.pad] * (self.bs - len(y_ids))

        return torch.tensor(x_ids, dtype=torch.long), torch.tensor(y_ids, dtype=torch.long)


# Training functions
def pretrain_model():
    raw = open(raw_text_path, 'r', encoding='utf-8').read()
    data = torch.tensor(encode(raw), dtype=torch.long)
    n_train = int(0.9 * len(data))
    train_raw, val_raw = data[:n_train], data[n_train:]

    train_dataset = PretrainDataset(train_raw, block_size=pretrain_block_size)
    train_loader = DataLoader(
        train_dataset,
        batch_size=pretrain_batch_size,
        shuffle=True,
        num_workers=2,
        pin_memory=True
    )

    model = GPTLanguageModel(pretrain_block_size).to(device)
    optim = torch.optim.AdamW(model.parameters(), lr=pretrain_lr)

    for epoch in range(pretrain_epochs):
        model.train()
        total_loss = 0
        for xb, yb in tqdm(train_loader, desc=f"Pretrain Epoch {epoch + 1}"):
            xb, yb = xb.to(device), yb.to(device)
            _, loss = model(xb, yb)
            optim.zero_grad()
            loss.backward()
            optim.step()
            total_loss += loss.item()

        print(f"Epoch {epoch + 1} - Loss: {total_loss / len(train_loader):.4f}")

    torch.save(model.state_dict(), checkpoint_base)
    return model



def finetune_model(model):
    if os.path.isfile(qa_data_json):
        qa_items = json.load(open(qa_data_json, 'r', encoding='utf-8'))
        print("qa_items[0]", qa_items[0])
    else:
        raise FileNotFoundError(f"{qa_data_json} not found")
    split = int(0.9 * len(qa_items))
    train_qa = DataLoader(QADataset(qa_items[:split]), batch_size=finetune_batch_size, shuffle=True)
    val_qa = DataLoader(QADataset(qa_items[split:]), batch_size=finetune_batch_size)

    optim = torch.optim.AdamW(model.parameters(), lr=finetune_lr)

    for epoch in range(finetune_epochs):
        model.train()
        total_loss = 0

        for xb, yb in tqdm(train_qa, desc=f"Finetune Epoch {epoch + 1}"):
            xb, yb = xb.to(device), yb.to(device)
            _, loss = model(xb, yb)
            optim.zero_grad()
            loss.backward()
            optim.step()
            total_loss += loss.item()

        avg_loss = total_loss / len(train_qa)
        print(f"Epoch {epoch + 1} - Loss: {avg_loss:.4f}")

        # Save checkpoint
        torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optim.state_dict(),
            'loss': avg_loss,
        }, checkpoint_latest)

        # Generate sample after each epoch - get original item from dataset
        sample_idx = 0  # or any index you want to use
        original_item = qa_items[split + sample_idx]  # Get from validation portion
        generate_sample(model, original_item)

    return model


def generate_sample(model, sample_item, max_new_tokens=50, max_context_length=400):
    model.eval()
    with torch.no_grad():
        context = sample_item['context']
        question = sample_item['question']

        # Truncate context if needed
        if len(context) > max_context_length:
            context = context[:max_context_length]

        prompt = f"[CONTEXT] {context} [QUESTION] {question} [ANSWER]"

        input_ids = encode(prompt)
        if len(input_ids) > max_context_length:
            input_ids = input_ids[:max_context_length]

        input_tensor = torch.tensor([input_ids], dtype=torch.long).to(device)
        # Generate answer
        output_ids = model.generate(
            input_tensor,
            max_new_tokens=max_new_tokens,
            temperature=0.7,
            top_k=20
        )

        # Decode and clean output
        full_output = decode(output_ids[0].tolist())
        answer = full_output.split('[ANSWER]')[-1].strip()

        print("\nSample Generation:")
        print(f"Context: {context}")
        print(f"Question: {question}")
        print(f"Generated Answer: {answer}")
        print("-" * 50)

    # def generate_sample(model, sample_item, max_new_tokens=50):
    #         model.eval()
    #         with torch.no_grad():
    #             # Prepare prompt
    #             context = sample_item['context']
    #             question = sample_item['question']
    #             prompt = f"[CONTEXT] {context} [QUESTION] {question} [ANSWER]"
    #
    #             input_ids = encode(prompt)
    #             input_tensor = torch.tensor([input_ids], dtype=torch.long).to(device)
    #
    #             # Generate answer
    #             output_ids = model.generate(
    #                 input_tensor,
    #                 max_new_tokens=max_new_tokens,
    #                 temperature=0.7,
    #                 top_k=20
    #             )
    #
    #             # Decode and clean output
    #             full_output = decode(output_ids[0].tolist())
    #             answer = full_output.split('[ANSWER]')[-1].strip()
    #
    #             print("\nSample Generation:")
    #             print(f"Context: {context}")
    #             print(f"Question: {question}")
    #             print(f"Generated Answer: {answer}")
    #             print("-" * 50)

        # Rest of your generation code...

# Main execution
if __name__ == "__main__":
    # Load or pretrain model
    if os.path.exists(checkpoint_base):
        model = GPTLanguageModel(finetune_block_size).to(device)
        model.load_state_dict(torch.load(checkpoint_base))
        print("Loaded pretrained model")
    else:
        print("Pretraining model...")
        model = pretrain_model()

    # Finetune on QA data
    model = finetune_model(model)

    # Final sample generation
    if os.path.isfile(qa_data_json):
        qa_items = json.load(open(qa_data_json, 'r', encoding='utf-8'))
        generate_sample(model, qa_items[0], max_new_tokens=100)
